# Generated by Django 3.1.1 on 2020-10-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='w_region',
            field=models.CharField(choices=[('선택없음', '시, 도를 먼저 선택해주세요')], default='시, 도를 먼저 선택해주세요', max_length=7),
        ),
    ]
