# Generated by Django 3.1.1 on 2020-11-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=15, unique=True)),
                ('personnel', models.PositiveIntegerField()),
                ('team_image', models.ImageField(blank=True, upload_to='team_image')),
                ('region', models.CharField(choices=[('경기', '경기도'), ('강원', '강원도'), ('경북', '경상북도'), ('경남', '경상남도'), ('충북', '충청북도'), ('충남', '충청남도'), ('전북', '전라북도'), ('전남', '전라남도'), ('제주', '제주도')], max_length=7)),
                ('phone', models.CharField(max_length=11)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='team',
            field=models.ManyToManyField(help_text='원하는 팀은 선택하세요', to='account.Team'),
        ),
    ]
