# Generated by Django 3.1.1 on 2020-10-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201020_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='my_team',
            field=models.CharField(default='없음', max_length=16),
        ),
    ]
