# Generated by Django 3.1.1 on 2020-11-25 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201125_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='team',
            new_name='teams',
        ),
    ]
