# Generated by Django 3.1.1 on 2020-10-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community_post',
            old_name='createDate',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='community_post',
            name='updateDate',
        ),
        migrations.AddField(
            model_name='community_post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
