# Generated by Django 3.1.1 on 2020-11-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20201022_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='num_hit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='블로그 글의 분류를 입력하세요.', max_length=50),
        ),
    ]
