# Generated by Django 3.1.1 on 2020-11-30 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game_Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.CharField(max_length=15, null=True)),
                ('coner', models.PositiveIntegerField(default=0)),
                ('penalty', models.PositiveIntegerField(default=0)),
                ('offside', models.PositiveIntegerField(default=0)),
                ('warn', models.PositiveIntegerField(default=0)),
                ('late', models.BooleanField(default=False)),
                ('foul', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Team_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('title_image', models.ImageField(blank=True, upload_to='image')),
                ('content', models.TextField()),
                ('importent', models.CharField(choices=[('일반', '일반'), ('공지사항', '공지사항')], max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
                ('team_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_right', models.CharField(max_length=15)),
                ('team_left', models.CharField(max_length=15)),
                ('place', models.CharField(max_length=25, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('finish', models.BooleanField(default=False)),
                ('results', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teampage.game_result')),
            ],
        ),
    ]
